WZ2100LEGACY(7)
==============
:doctype: manpage

NAME
----
wz2100legacy - What Warzone 2100 was meant to be

SYNOPSIS
--------
*wz2100legacy* ['OPTIONS']

DESCIPTION
----------

This manual page documents briefly the wz2100legacy command.

Warzone 2100 Legacy is Warzone 2100 the way it was meant to be.

OPTIONS
-------

*--cheat*::
      Run in cheat mode.

*--datadir*='DIR'::
      Set default datadir to 'DIR'.

*--debug*='FLAG'::
      Show debug for 'FLAG', use this several times for several flags. Useful
      flags include 'wz', '3d', 'sound', 'video'. 'all' gives all of that and
      much more.

*--debugfile*='FILE'::
      Log debug output in 'FILE'.

*--fullscreen*::
      Play in fullscreen mode.

*--help*::
      Show help and exit.

*--mod*='MOD'::
      Enable global mod 'MOD'.

*--mod_ca*='MOD'::
      Enable campaign only mod 'MOD'.

*--mod_mp*='MOD'::
      Enable multiplay only mod 'MOD'.

*--savegame*='NAME'::
      Load a saved game 'NAME' (needs to include the .gam extension).

*--window*::
      Play in windowed mode.

*--masterserver*='warzonelegacy.org'::
      Set IP or domain to use for the lobby server.

*--masterserver-port*='4444'::
      Set port number for the lobby server. Default is 9990.

*--version*::
      Output version info and exit.

*--resolution*='WIDTHxHEIGHT'::
      Run  at 'WIDTH' times 'HEIGHT' screen resolution. This needs to be a
      resolution supported by your X server.

*--(no)shadows*::
      Toggle the shadows.

*--(no)sound*::
      Toggle the sound.
      
*--(no)texturecompression*::
      Control texture compression. Some older video cards may require this to work properly.
      
*--selftest*::
      Run a self test. Currently broken.

The masterserver/port, fullscreen/window, resolution,  sound,  and  shadows  settings  are
stored,  so  they  only  need to be specified once, or when you want to
change them.

EXAMPLES
--------
'wz2100legacy --fullscreen --resolution=800x600'::
      Run in full screen at 800x600 screen resolution.

'wz2100legacy --window --resolution=800x600'::
      Run in a window at 800x600 screen resolution.

'wz2100legacy'::
      Run the game, with the last used resolution, fullscreen/window, sound and
      shadow settings.

AUTHORS
-------

See the copyright file included in the package.

This manual page was originally written by Linas Zvirblis  <0x0007@gmail.com>
for the Debian project, and modified by the Warzone project, and then by the Warzone 2100 Legacy project.
